### ISSUE TITLE
Doesn't take care of tailwind's base layer (resets)

### ISSUE THREAD

**Issue by jkohlin** [dolanmiu/vite-plugin-scope-tailwind#2]
It still doesn't fix the html element resets that Tailwind does, which was my actual problem:
```css 
#tailwincss
h1, h2, h3, h4, h5, h6 {
    font-size: inherit;
    font-weight: inherit;
}
``` 
![CleanShot 2023-11-15 at 15 03 11](https://github.com/dolanmiu/vite-plugin-scope-tailwind/assets/4112881/0915a611-65fe-48e4-a453-b2a9f8e17f17)

What can I do to fix that?
